# Generated by Django 3.0.7 on 2020-07-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=11, unique=True)),
                ('requestURL', models.CharField(max_length=1000, unique=True)),
                ('responseURL', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
